backend/api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('api/register/', register, name='register'),
    path('api/login/', user_login, name='login'),
    path('api/travelogue/', travelogue_api, name='travelogue'),
    path('api/article/', article_api, name='article'),

]

backend/main/urls.py
from django.urls import path
from .views import *

app_name = "main"

urlpatterns = [
    path('', index, name='index'),
    path('travelogues/', travelogues, name='travelogues'),
    path('places/', places, name='places'),
    path('travelogue/<slug:slug>', travelogue, name='travelogue'),
    path('write/', write, name='write'),


]

backend/tourism/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('', include('main.urls')),

]

backend/main/models.py
# models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission
from django.db import models
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
import secrets
import string
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager

class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, username, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    # Additional custom fields
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    # Many-to-many relationship with groups and permissions
    groups = models.ManyToManyField(Group, verbose_name='groups', blank=True, related_name='custom_users')
    user_permissions = models.ManyToManyField(
        Permission, verbose_name='user permissions', blank=True, related_name='custom_users'
    )

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'

    def __str__(self):
        return self.username


class Category(models.Model):
    title = models.CharField(max_length=100)
    latin = models.CharField(max_length=300)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, *kwargs)
        if not self.slug:
            now = datetime.now()
            self.slug = slugify(self.latin)+"-"+str(now.year)+"-"+str(now.month)+"-"+str(now.day)+"-"+str(self.id)
            self.save()
    
class Tag(models.Model):
    title = models.CharField(max_length=100)
    latin = models.CharField(max_length=300)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, *kwargs)
        if not self.slug:
            now = datetime.now()
            self.slug = slugify(self.latin)+"-"+str(now.year)+"-"+str(now.month)+"-"+str(now.day)+"-"+str(self.id)
            self.save()
    
class Article(models.Model):
    title = models.CharField(max_length=300)
    latin = models.CharField(max_length=300)
    article = models.TextField()
    cover = models.ImageField(upload_to="covers/")
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    upload_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    tags = models.ManyToManyField(Tag)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, *kwargs)
        if not self.slug:
            now = datetime.now()
            self.slug = slugify(self.latin)+"-"+str(now.year)+"-"+str(now.month)+"-"+str(now.day)+"-"+str(self.id)
            self.save()

class City(models.Model):
    name = models.CharField(max_length=100)
    latin = models.CharField(max_length=300)
    cover = models.ImageField(upload_to='cities/')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, *kwargs)
        if not self.slug:
            now = datetime.now()
            self.slug = slugify(self.latin)+"-"+str(now.year)+"-"+str(now.month)+"-"+str(now.day)+"-"+str(self.id)
            self.save()

class Travelogue(models.Model):
    title = models.CharField(max_length=300)
    latin = models.CharField(max_length=300)
    content = models.TextField()
    uploader = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    upload_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)

    def __str__(self):
            return self.title

    def save(self, *args, **kwargs):
        super().save(*args, *kwargs)
        if not self.slug:
            now = datetime.now()
            self.slug = slugify(self.latin)+"-"+str(now.year)+"-"+str(now.month)+"-"+str(now.day)+"-"+str(self.id)
            self.save()

class Token(models.Model):
    key = models.CharField(max_length=40, primary_key=True)
    user = models.OneToOneField(CustomUser, related_name='auth_token', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
        return super(Token, self).save(*args, **kwargs)

    def generate_key(self):
        chars = string.ascii_letters + string.digits
        return ''.join(secrets.choice(chars) for i in range(40))


@receiver(post_save, sender=CustomUser)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

backend/main/views.py
from django.shortcuts import render
from .models import Travelogue, City

def index(request):
    travelogues = Travelogue.objects.all()[0:3]
    cities = City.objects.all()[0:8]
    return render(request, "main/index.html", {
        "travelogues": travelogues,
        "cities": cities,
        "page": "home"
    })

def travelogues(request):
    travelogues = Travelogue.objects.all()
    
    return render(request, "main/travelogues.html", {
        "travelogues": travelogues,
        "page": "travelogues"
        
    })

def travelogue(request, slug):
    travelogue = Travelogue.objects.get(slug=slug)

    return render(request, "main/travelogue.html", {
        "travelogue": travelogue,
    })

def places(request):
    cities = City.objects.all()

    return render(request, "main/places.html", {
        "cities": cities,
        "page": "places"
    })

def write(request):
    cities = City.objects.all()

    return render(request, "main/write.html", {
        "page": "write"
    })

backend/templates/main/index.html
{% extends "main/layout.html" %}
{% load static %}
{% block body %}
    <br>
    <div class="center h-img">
        <img src="{% static 'main/assesst/image/header/header.png' %}" alt="">
    </div>
<main>
    <div class="body-div">
        <h2 class="title">Popular cities</h2>
        <div class="c-container">
            {% for city in cities %}
            <a href="{% url 'main:travelogues' %}">
                <div class="c-img">
                    <img src="{{city.cover.url}}" alt="picture of {{city.name}}">
                    <div class="top-left">{{city.name}}</div>
                </div>
            </a>
            {% endfor %}
        </div>
        <h2 class="title">Popular travelogues</h2>
        <div class="c-container">
            {% for t in travelogues %}
            <div class="t-box">
                <h3>{{t.title}}</h3>
                <p style="text-align: left;">{{t.content|truncatewords:20}}
                    <br>
                    <a href="{% url 'main:travelogue' t.slug %}">more...</a>
                </p>
            </div>
            {% endfor %}
        </div>
        <br>
    </div>
    <br>
    <div class="b-container">
        <img src="{% static 'main/assesst/image/homepage/blog.png' %}" alt="Blog">
        <div class="centered">
            <h2>Blogs</h2>
            <b>Read articles about popular countries and <br>
            cities in the world and learn more about them
            </b>
            <br> <br>
            <a class="btn" href="">Read more</a>
        </div>
    </div>
    <br>
    <div class="body-div">
        <div>
            <b class="map-t">Here you can read articles and</b>
            <br>
            <b class="map-t">travelogues of the whole world</b>
        </div>
        <br>
        <br>
        <div class="map">
            <img src="{% static 'main/assesst/image/homepage/map.png' %}" alt="world's map">
        </div>
    </div>
    <br>
    <div class="t-write">
        <div>
            <img src="{% static 'main/assesst/image/homepage/travelogue.png' %}" alt="write travelogue">
        </div>
        <div class="b-write">
            <b class="map-t">Do you also want to write your own travelogue?</b>
            <br>
            <b class="map-t">So come to this page</b>
            <br>
            <br>
            <a class="w-btn btn" href="{% url 'main:write' %}">write travelogue</a>
        </div>
    </div>
</main>
{% endblock body %}

backend/templates/main/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Traex</title>
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>

</head>
<body>
    <header>
        <div class="header-wrapper">
            <div class="header">
              <div class="cantainer">
                <div class="logo">
                  <h1 style="display: none" >Traex</h1>
                  <img id="logo" src="{% static 'main/assesst/image/logo/logo.png' %}" alt="logo"/>
                </div>
                <div class="menu">
                  <ul>
                    <li {% if page == "home" %}class="selected"{% endif %}>
                      <a href="{% url 'main:index' %}">Home</a>
                    </li>
                    <li {% if page == "travelogues" %}class="selected"{% endif %}>
                      <a href="{% url 'main:travelogues' %}">Travelogues</a>
                    </li>
                    <li {% if page == "places" %}class="selected"{% endif %}>
                      <a href="{% url 'main:places' %}">Places</a>
                    </li>
                    <li {% if page == "write" %}class="selected"{% endif %}>
                      <a href="{% url 'main:write' %}">Write</a>
                    </li>
                    <li {% if page == "ai" %}class="selected"{% endif %}>
                      <a href="#">AI(BETA)</a>
                    </li>
                    <li {% if page == "blog" %}class="selected"{% endif %}>
                      <a href="#">Blog</a>
                    </li>
                  </ul>
                </div>
                <a href="#" class="selected">
                  Login
                </a>
              </div>
            </div>
        </div>
    </header>
    {% block body %}
    {% endblock body %}
    <footer>
        <img src="{% static 'main/assesst/image/footer/footer.png' %}" alt="">
    </footer>
</body>
</html>

backend/templates/main/places.html
{% extends "main/layout.html" %}
{% load static %}
{% block body %}
<main>
    <div class="body-div">
        <div class="c-container">
            {% for city in cities %}
            <a href="{% url 'main:travelogues' %}">
                <div class="c-img">
                    <img src="{{city.cover.url}}" alt="picture of {{city.name}}">
                    <div class="top-left">{{city.name}}</div>
                </div>
            </a>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock body %}

backend/templates/main/travelogue.html
{% extends "main/layout.html" %}
{% load static %}
{% block body %}
<main>
    <div>
        <h1 class="text-2">{{travelogue.title}}</h1>
        <div class="t-border">
            <div class="t-body">
                <p>
                    {{travelogue.content}}
                </p>
            </div>
            <div class="t-comment comment">
                <div class="text-like">
                    <img class="viwe" src="{% static 'main/assesst/image/travel/viwe.png' %}" alt="viwe" />
                    <P>103</P>
                </div>
                <div class="text-like" >
                    <img class="like" src="{% static 'main/assesst/image/travel/like.png' %}"  alt="like"/>
                    <p>102</p>
                    
                </div>
                <p class="diat"> 31 OCTOBER 2023</p>
            </div>
        </div>
    </div>
                
</main>
{% endblock body %}

backend/templates/main/travelogues.html
{% extends "main/layout.html" %}
{% load static %}
{% block body %}
<main>
    <div class="aftter-header">
        <h2 class="text-2">Travelogues</h2>
    </div>
    <div class="center-d">
        <div class="button-box">
            <a href="#" class="selected">
            Newest
            </a>
            <a href="#" class="titre">
            Most visited
            </a>
            <a href="#" class="titre">
            Most visited
            </a>
            <a href="#" class="titre">
            Most Popular
            </a>
        </div>
    </div>
    <div class="wrapper-card">
        <div class="cantainer">
            <div class="all-card">
                {% for t in travelogues %}
                <div class="card">
                    <h3 class="text-card">
                        {{t.title}}
                    </h3>
                    <p style="text-align: left;">{{t.content|truncatewords:40}} <br> <a href="{% url 'main:travelogue' t.slug %}"><b>more...</b></a></p>
                    <div class="comment">
                        <div class="text-like">
                            <img class="viwe" src="{% static 'main/assesst/image/travel/viwe.png' %}" alt="viwe" />
                            <P>103</P>
                        </div>
                        <div class="text-like" >
                            <img class="like" src="{% static 'main/assesst/image/travel/like.png' %}"  alt="like"/>
                            <p>102</p>
                            
                        </div>
                        <p class="diat"> 31 OCTOBER 2023</p>
                    </div>
                </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock body %}

backend/templates/main/write.html
{% extends "main/layout.html" %}
{% load static %}
{% block body %}
<main>
    <div class="aftter-header">
        <h2 class="h2">Write</h2>
        <h3 class="h3">We can shere about your travelogue</h3>
    </div>
    <div class="wrapper-box">
    <div class="box">
        <from>
            <div class="first-section">
                <div class="text-contact">
                    <legend>
                        Contact Details
                    </legend>
                </div>
                <label for="name">Name</label>
                <input autofocus
                type="text" id="name"
                name="name" autofocus
                placeholder="name"
                required/><br></br>
                <label for="email">Email</label>
                <input type="email" id="email"
                placeholder="ob2@hotmail.com"/><br></br>
                <label for="tel">Phone</label>
                <input type="tel" id="tel" placeholder="+233 200001212"/><br></br>
            </div>
        </from>
    </div>
    <div class="box">
        <form>
            <div class="text-contact">
                <legend >
                    Your Travelogue
                </legend>
            </div>
            <div class="first-section">
                <label for="Travelogue-name">Your Travelogue’s name:
                </label>
                <input autofocus
                type="Your Travelogue’s name:" id="Travelogue-name"
                name="Travelogue-name" autofocus
                placeholder="My Best Travel"
                required/><br></br>
                <label for="Locations">Locations:</label>
                <input type="Locations" id="Locations"
                name="Locations" autofocus
                placeholder="England,London-England,Manchester"
                required/><br></br>
                
                <div class="second-section">
                <legend>
                    write your memories
                </legend>
                <p>
                    please mention the names of
                    the places you went while writing
                    your memories
                </p>
                <div class="memories">
                    <textarea autofocus
                    type="text" id="memories"
                    name="memories" cols="45" rows="10" autofocus
                    placeholder="description"></textarea><br><br>
                </div>
            </div>
            <!-- <div>
                <input type="checkbox" id="scales" name="scales" class="checkbox">
                <label for="scales"> have read and agree</label>
            </div> -->
            <button>Submit</button>    
        </form>
    </div>

      



</div>

        </form>
    </div>

            </div>
</main>
{% endblock body %}
    <!--                <label for="dob">BirthDay</label>-->
    <!--                <input type="date" id="dob"/><br></br>-->
    <!--                <label for="gender"> Gender ?? </label>-->
    <!--                <input list="genders" name="gender" id="gender"/>-->
    <!--                <datalist id="genders"></datalist>-->
    <!--                    <option value="female"></option>-->
    <!--                    <option value="male"></option>-->
    <!--                    <option value="other"></option>-->